---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-gateway
  namespace: echo-gateway
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik-external
  rules:
  - host: echo-gateway.localhost
    http:
      paths:
      - backend:
          service:
            name: echo-gateway
            port:
              name: https
        path: /echo
        pathType: Prefix
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name:  echo-gateway-internal
  namespace: echo-gateway
spec:
  spiffe:
    mode: mTLS
    clientIDs:
      - "spiffe://demo.voiapp.io/ns/traefik-external/sa/traefik-external"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-gateway-internal
  namespace: echo-gateway
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: spiffe
    traefik.ingress.kubernetes.io/router.tls.options: echo-gateway-echo-gateway-internal@kubernetescrd
spec:
  ingressClassName: traefik-internal
  rules:
  - host: echo-internal.localhost
    http:
      paths:
      - backend:
          service:
            name: echo-gateway
            port:
              name: https
        path: /echo
        pathType: Prefix
